INSERT INTO category(id, name) VALUES(0,"디지털 기기");
INSERT INTO category(id, name) VALUES(1,"게임/취미");
INSERT INTO category(id, name) VALUES(2,"여성패션/잡화");
INSERT INTO category(id, name) VALUES(3,"뷰티/미용");
INSERT INTO category(id, name) VALUES(4,"생활 가전");
INSERT INTO category(id, name) VALUES(5,"생활/가공식품");
INSERT INTO category(id, name) VALUES(6,"남성패션/잡화");
INSERT INTO category(id, name) VALUES(7,"반려동물");
INSERT INTO category(id, name) VALUES(8,"가구 인테리어");
INSERT INTO category(id, name) VALUES(9,"스포츠/레저");
INSERT INTO category(id, name) VALUES(10,"유아동");
INSERT INTO category(id, name) VALUES(11,"도서/티켓");